# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobelt_app', '0003_auto_20161218_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_user', to='djangobelt_app.User'),
        ),
    ]
